<a href="https://colab.research.google.com/github/myllenammartins/API-RESTful/blob/main/WMC_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Explorando Ecossistemas:**
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo
abaixo demonstra dados das espécies encontradas,considere a
seguinte ordem de colunas:
* **IDdaespécie**,
* **quantidade de representantes encontrados**,
* **profundeza**,
* **tamanho médio da
espécie**.


In [ ]:
import numpy as np

In [ ]:
especies = np.array([[747, 89, 33, 5],
                   [623, 123, 32, 13],
                   [501,22,49,2],
                   [116,101,42,10],
                   [297,56,69,22],
                   [613,64,27,7],
                   [295,84,29,14],
                   [692,105,72,16],
                   [229,103,35,5],
                   [374,124,70,1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

A. Selecione a
segunda coluna com a ***quantidade de espécies encontradas*** e adicione em um
array as **qtd_especies**.

In [ ]:
qtd_especies = especies[:, 1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

B. De **qtd_especies** selecione apenas as primeiras 3 quantidades e print.

In [ ]:
print(qtd_especies[:3])

[ 89 123  22]


C. Print as 5 últimas quantidades de espécies.

In [ ]:
qtd_especies[-5:]

array([ 64,  84, 105, 103, 124])

In [ ]:
especies.shape

(10, 4)

D. Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.

In [ ]:
np.sort(especies[:, 3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [ ]:
np.sort(especies[:, 3])[::-1]

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

Usando um index boolean crie um array que contém os dados
 da maior espécie encontrada(considerando o seu tamanho),esse valor corresponde ao valor 22.

In [ ]:
especies[:, 3] == 22


array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
maior_especie = especies[especies[:, 3 == 22]]

Usando *fency* index faça um array que contém apenas dados da espécie com ID 297.

In [ ]:
mask_297 = especies[:, 0] == 297

In [ ]:
especies[mask_297]

array([[297,  56,  69,  22]])

Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

In [ ]:
np.where(especies[:, 1] == 105)

(array([7]),)

In [ ]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  16]])

Considere a profundeza em que o a espécie foi encontrada substitua valores maiores que 60 com "Profundo”


In [ ]:
especies[:, 2] > 60

array([False, False, False, False,  True, False, False,  True, False,
        True])

In [ ]:
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U21')

# ADICIONANDO E REMOVENDO DADOS DO ARRAY

Adicione mais 2 espécies ao array: [[204,10,40,12],[392,11,81,11]]

In [ ]:
novas_especies = np.array([[204,10,40,12],[392,11,81,11]])

In [ ]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0].

In [ ]:
especies.shape

(10, 4)

In [ ]:
ver = np.array([0,1,0,0,0,0,1,0,1,1]).reshape((10, 1))
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [ ]:
np.concatenate((especies, ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])

# Salvando array

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [ ]:
arr3d.shape

(2, 2, 3)